name: Test Actions Workflow
on:
  push:
    branches: [master]

jobs:
  JOB1-scripts:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered from repository ${{ github.repo }}"
