#########################################################
# Concurrency allows to run 1 cycle at a time
# If worflow is running, 2nd one will automatically go in pending state if concurrency is enabled
# If 1st running, 2nd in pending and 3rd is triggered then 2nd which was in pending will be cancelled and 
# only 3rd (latest) will run

  # If this is enabled it will cancel current running and start latest
  # cancel-in-progress: true

###########################################################

name: Concurrency Test
on:
  #Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# Concurrency can be used at workflow level or job leve
concurrency:
  group: build-and-test
  
  # If this is enabled it will cancel current running and start latest
  cancel-in-progress: true


jobs:
   build-and-test-on-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
# Adding sleep time to keep one running and trigger 2nd to check concurrency
      - name: Build and code sim
        run: |
          echo "Starting the code build"
          sleep 3m
          echo "Finish the code build"