name: Concurrency Test
on:
  Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# Concurrency can be used at workflow level or job leve

concurrency:
  group: build-and-test


jobs:
   build-and-test-on-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build and code sim
        run: |
          echo "Starting the code build"
          sleep 1m
          echo "Finish the code build"