####################################################################
# Returns True when none of previous steps have failed or cancelled
####################################################################

name: ConditionsTest

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
   branches: [ master ]
  pull_request:
   branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  JOB1-push:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
    # If you dont specify name for step, it will show command as name
      - name: "Check condition"
        run: echo "This run on push"   
      - run: echo "${{ github.event_name }}"
  JOB2-pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: "Run some steps"
        run: echo "hello"
      - name: "Run More steps"
        run: echo "World"      
      - name: "Check Previous Steps success"
        if: ${{ success() }}
        run: echo "Previous job was a success"