name: Context test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Dump_Context_to_log:
    runs-on: ubuntu-latest
    steps:
    # This will print all runner contexts, see github docs or print like this to see all and then choose 
      - name: "Dump Runner Context"
        run: echo "${{ toJSON(runner) }}"
    # You can drill to individual as well
      - run: echo "${{ runner.os }}"
      - run: echo "${{ runner.workspace }}"
      