name: Context test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Dump_Context_to_log:
    runs-on: ubuntu-latest
    steps:
    # This will print all runner contexts, see github docs or print like this to see all and then choose 
    ###############################################################################################
    # RUNNER CONTEXTS
    ################################################################################################
      - name: "Dump Runner Context"
        run: echo "${{ toJSON(runner) }}"
    # You can drill to individual as well
      - run: echo "Printing runner OS- ${{ runner.os }}"
      - run: echo "Printing runner workspace path- ${{ runner.workspace }}"
    
    # There are many other contexts you can use.print all to see or see github docs for each
    # This prints all
    ###############################################################################################
    # GITHUB CONTEXTS
    ################################################################################################
      - name: "Dump Github Contexts"
        run: echo '${{ toJSON(github) }}'

        #individual github contexts values
      - run: echo "Printing repo - ${{ github.repository }}"
      - run: echo "Printing repo url - ${{ github.repositoryUrl }}"
      - run: echo "Printing sha- ${{ github.sha }}"
      - run: echo "Printing branch- ${{ github.ref }}"
    ###############################################################################################
    # JOBS CONTEXTS
    ################################################################################################
      - name: "Dump JOB Contexts"
        run: echo '${{ toJSON(job) }}' 
        run:  echo "JOB STATUS is- ${{ job.status }}"
    ###############################################################################################
    # STEPS CONTEXTS
    ################################################################################################
      - name: "Dump Steps Contexts"
        run: echo '${{ toJSON(steps) }}'
      - run: echo '${{ steps.name }}'
    ###############################################################################################
    # STRATEGY CONTEXTS
    ################################################################################################
      - name: "Dump strategy Contexts"
        run: echo '${{ toJSON(strategy) }}'
    ###############################################################################################
    # MATRIX CONTEXTS
    ################################################################################################
      - name: "Dump matrix Contexts"
        run: echo '${{ toJSON(matrix) }}'