name: Test Dependencies
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  initial:
    runs-on: ubuntu-latest
    steps:
      - run : echo "This will run first"
  job2:
    runs-on: ubuntu-latest
    needs: initial
    steps:
      - run : echo "This will run after intial job finishes"
  job3:
    runs-on: ubuntu-latest
    needs: initial
    steps:
      - run : echo "This will run after intial and in parallel with job2"
  job4:
    runs-on: ubuntu-latest
    needs: [initial, job2]
    steps:
      - run : echo "This will run after intial and in parallel to job3"
  job5:
    runs-on: ubuntu-latest
    needs: [job2, job3]
    steps:
      - run : echo "This will run after job2 and job3 have finished"
  