name: Test Dependencies
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run : echo "This will run first"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run : echo "This will run after job1"
  job3:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run : echo "This will run in parallel with job1"
  job3:
    runs-on: ubuntu-latest
    needs: [job1, job1]
    steps:
      - run : echo "This will run after job1 and in parallel to job2"
  job4:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
      - run : echo "This will run after job1 and job2 have finished"
  