name: Environments Test
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DEV_URL: "https://docs.github.com/en/developers"
  PROD_URL: "https://docs.github.com/"
  DEV_CONFIG: "abcsnapshot"
  PROD_CONFIG: "abcrelease"


jobs:
  DEV:
    runs-on: ubuntu-latest
    # An environment can be specified per job
    # If the environment cannot be found, it will be created
    environment: 
      name: DEV
      url: ${{ env.DEV_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Step that uses the DEV environment
        run: echo "Deployment to ${{ env.DEV_URL }} "
      
      - name: Step that uses the DEV config
        run: echo "Config is ${{ env.DEV_CONFIG }} "

  PROD:
    runs-on: ubuntu-latest
    needs: DEV
    # An environment can be specified per job
    # If the environment cannot be found, it will be created
    environment: 
      name: PROD
      url: ${{ env.PROD_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Step that uses the PROD environment
        run: echo "Deployment to ${{ env.PROD_URL }} "
      
      - name: Step that uses the PROD config
        run: echo "Config is ${{ env.PROD_CONFIG }} "
          
