#You can use the jobs.<job_id>.if conditional to prevent a job from running unless a condition is met. 
#When you use expressions in an if conditional, 
#you may omit the expression syntax (${{ }}) because GitHub automatically evaluates 
#You can use the jobs.<job_id>.if conditional to prevent a job from running unless a condition is met. You can use any supported context and expression to create a conditional.
# When you use expressions in an if conditional, you may omit the expression syntax (${{ }}) because GitHub automatically evaluates the if conditional as an expression. the if conditional as an expression. 
name: IF ELSE Conditions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # push:
  #  branches: [ master ]
  # pull_request:
  #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  JOB1-push:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
    # If you dont specify name for step, it will show command as name
      - name: "Check condition"
        run: echo "This run on push"   
      - run: echo "${{ github.event_name }}"

# We pushing here so this wont run and show skipped on github
  JOB2-pull_request:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
    # If you dont specify name for step, it will show command as name
      - name: "Check condition"
        run: echo "This run on pull request"   
      - run: echo "${{ github.event_name }}"
  
  job3:
    runs-on: ubuntu-latest
    # if statement without  ${{ }} as if keyword evaluates itself
    if: runner.os == 'ubuntu-latest'
    steps:
      run: echo "This will run if runner os is ubuntu latest"

  job4:
    runs-on: windows-latest
    # if statement without  ${{ }} as if keyword evaluates itself
    if: runner.os == 'ubuntu-latest'
    steps:
      - run: echo "This wont run"
  
