name: JavaCI
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    # An environment can be specified per job
    # If the environment cannot be found, it will be created
    steps:
    # Repository secret
    # Secret set in UI in repo settings under secrets
      - name: Secret Test
        run: echo "helo"