# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  JOB1-RunScripts:
    runs-on: ubuntu-latest
    steps:
      - name: "Say Hello step"
        run: echo "Hello Action"
    
      - name: "Repository Info"
        run: echo "This event is triggered from-  ${{ github.repository }} repository"
# If you dont specify name, it will show command as name
      - run: echo "The branch is  ${{ github.ref }} "
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      

