# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  JOB1-RunScripts:
    runs-on: ubuntu-latest
    steps:
    # If you dont specify name for step, it will show command as name
      - name: "Say Hello step"
        run: echo "Hello Action"
    
      - run: echo "Printing Repository Info"
      - run: echo "This event is triggered from-  ${{ github.repository }} repository"
      - run: echo "The branch is  ${{ github.ref_name }} "
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "Repo Url- ${{ github.repositoryUrl }} ."
      - run: echo "Commit SHA ${{ github.sha }} ."

      - run: echo "printing job info"
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "Workflow Job ID# ${{ github.job }}"

      - name: Check out repository code
        uses: actions/checkout@v2
      
      - name: Workspace details
        run:  echo '${{ github.workspace }}'

      - name: List files in workspace
        run: ls ${{ github.workspace }}
    
      - name: Print current directory
        run : pwd  
      
      - name: Running multiple runs in 1 step
        run: |
          echo "Running two commands ${{ pwd }}" 
          echo "This is second command printing run id ${{ github.run_id }}"

      - name: "Print Job Status"
        run: echo " ${{ job.status }}"

      

