####################################################################
# Use needs to get output from 1 job into current job
####################################################################

name: needsTest
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    # Set this Jobs output in build_id var
    outputs: 
      output1: $ {{ steps.step1.outputs.test }}
    steps:
      - id: step1
        run: echo "::set-output name=test::hello"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Printing Outputs"
          echo ${{ needs.job1.outputs.output1 }}