#######################################################################
# This is workflow that will be called by another workflow
# It should have workflow_call as on event
# A reusable workflow cannot be called inside another reuseable workflow
# You cannit inherit variables, you have to explicitly pass them
# It can contain other triggers aparts from workflow_call
########################################################################
name: Reuse Workflow
on:
  # Must have workflow_Call for a reuse workflow
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag:
        type: string
      # secrets:
      #   registry_username:
      #     required: true
      #   registry_password:
      #     required: true
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Print inputs
        run: |
          echo ${{ github.event.inputs.image_name }}
          echo ${{ github.event.inputs.tag }}
      
