###############################################################
# We are calling reuseworkflow.ymk
#################################################################

name: Reuse Workflow caller
on:
  #Triggers the workflow on push or pull request events but only for the master branch
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      build_id:
        required: true
        type: number
      deploy_target:
        type: string
        required: true

jobs:
  deploy_job:
    # provide path of workflow, it should be public, in same repo or same org
    uses: ankush56/helloWorld/.github/workflows/reuseworkflow.yml@master
    #Inputs and secrets are defined in parent workflow we calling. We provide values here
    with:
      build_id: 1
      deploy_target: "SERVER1"
      # secrets:
      #   registry_username: ${{ secrets.REG_USER }}
      #   registry_password: ${{ secrets.REG_PASS }}      