name: SecTest
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  DEV:
    runs-on: ubuntu-latest
    # An environment can be specified per job
    # If the environment cannot be found, it will be created
    environment: 
      name: DEV
      url: ${{ env.DEV_URL }}
    steps:
      - name: Secret Test
        run: "The value for DB_PASS is ${{ secrets.DB_PASS }}"
