#You can skip workflow runs triggered by the push and pull_request events 
#by including a command in your commit message.
# 
#    [skip ci]
#    [ci skip]
#    [no ci]
#    [skip actions]
#    [actions skip]
#

# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
   branches: [ master ]
  pull_request:
   branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  JOB1-RunScripts:
    runs-on: ubuntu-latest
    steps:
    # If you dont specify name for step, it will show command as name
      - name: "Say Hello step"
        run: echo "This wont run as we add skip ci in commit messsage"