##########################################################
# We added workflow status in readme.md
# You can display a status badge in your repository to indicate the status of your workflows.
#A status badge shows whether a workflow is currently failing or passing. 
#A common place to add a status badge is in the README.md file of your repository, 
#but you can add it to any web page you'd like. 
#By default, badges display the status of your default branch. 
#You can also display the status of a workflow run for a specific branch or event using the branch and event query parameters in the URL.
###########################################################
name: Status Badge
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # push:
  #   branches: [ feature/*, release/*, master ]
  # pull_request:
  #   branches: [ $default-branch  ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: heju
  JAVA_VERSION: '11'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  #checkout code

      - name: Print environments Vars
        run: |
          echo "${{ env.AZURE_WEBAPP_NAME }}"
          echo "${{ env.JAVA_VERSION }}"