####################################################################
# Build with different version of maven and Java
# Using Strategy and Matrix
# It will create 1 job with each matrix and its combinations
# Here we had total 9 cases(3 in each matrix, maven, java & mymatrix, it created total 27 jobs)
####################################################################

name: StrategyMatrix
on:
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]

  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    # Using Strategy and Matrix
    strategy:
      matrix:
        maven: [ '3.5.4', '3.6.3', '3.8.2' ]
        java: ['8' , '11', '16']
        myMatrix: ['Superman', 'Spiderman', 'Hulk']
    steps:
      - name: Setup Maven
        uses: s4u/setup-maven-action@v1.2.1
        with:
          java-version: ${{ matrix.java }}
          maven-version: ${{ matrix.maven }}
      - name: Build with Maven
        run: mvn verify
      
      - name: Test my matrix
        run: echo "This is matrix test for ${{ matrix.myMatrix }}"