name: Test Custom Action

# Controls when the workflow will run 
on: [push]

# A workflow run is made up of one or more  jobs that can run sequentially or in parallel
jobs:
  job1:
    name: Test Custom Hello world action in aw-action repo
    runs-on: ubuntu-latest
    steps:
      - id: foo
        uses: aw-action/Hello Action Metadata@main
        with:
          person: "Spiderman"
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash